name = "ExponentialFamilyManifolds"
uuid = "5c9727c4-3b82-4ab3-b165-76e2eb971b08"
authors = ["Mykola Lukashchuk <m.lukashchuk@tue.nl>, Dmitry Bagaev <bvdmitri@gmail.com> and contributors"]
version = "1.0.0"

[deps]
BayesBase = "b4ee3484-f114-42fe-b91c-797d54a0c67e"
ExponentialFamily = "62312e5e-252a-4322-ace9-a5f4bf9b357b"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"

[compat]
BayesBase = "1.3"
ExponentialFamily = "1.4"
Manifolds = "0.9"
ManifoldsBase = "0.15"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"

[targets]
test = ["Aqua", "Test", "ReTestItems"]
